### ISSUE TITLE
Running ../examples/train_model.py returns import error

### ISSUE THREAD

**Issue by MortenHolmRep** [icecube/graphnet#159]
With a clean installation of Anaconda3-2020.11, 'setup.py' and running '../examples/train_model.py' on HEP04 returns the following import error

(base) [qgf305@hep04 examples]$ python train_model.py
Traceback (most recent call last):
  File "train_model.py", line 3, in <module>
    from pytorch_lightning import Trainer
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/pytorch_lightning-1.5.9-py3.8.egg/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/pytorch_lightning-1.5.9-py3.8.egg/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/pytorch_lightning-1.5.9-py3.8.egg/pytorch_lightning/callbacks/base.py", line 26, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/pytorch_lightning-1.5.9-py3.8.egg/pytorch_lightning/utilities/types.py", line 25, in <module>
    from torchmetrics import Metric
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torchmetrics-0.7.0-py3.8.egg/torchmetrics/__init__.py", line 59, in <module>
    from torchmetrics.image import (  # noqa: E402
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torchmetrics-0.7.0-py3.8.egg/torchmetrics/image/__init__.py", line 14, in <module>
    from torchmetrics.image.inception import IS, InceptionScore  # noqa: F401
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torchmetrics-0.7.0-py3.8.egg/torchmetrics/image/inception.py", line 20, in <module>
    from torchmetrics.image.fid import NoTrainInceptionV3
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torchmetrics-0.7.0-py3.8.egg/torchmetrics/image/fid.py", line 38, in <module>
    import scipy
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/scipy/__init__.py", line 155, in <module>
    from . import fft
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/scipy/fft/__init__.py", line 74, in <module>
    from ._basic import (
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/scipy/fft/_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/scipy/_lib/uarray.py", line 28, in <module>
    from ._uarray import *
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/scipy/_lib/_uarray/__init__.py", line 115, in <module>
    from ._backend import *
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/scipy/_lib/_uarray/_backend.py", line 4, in <module>
    from . import _uarray  # type: ignore
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/scipy/_lib/_uarray/_uarray.cpython-38-x86_64-linux-gnu.so)

**Comment by MortenHolmRep** [comment]
Suggestion from @BozianuLeon was to set custom export paths by running the following

```
more .bashrc

export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

export PATH=/usr/local/cuda-10.1/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64:$LD_LIBRARY_PATH

export PATH=/usr/local/cuda-11.2/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=~/anaconda3/lib:$LD_LIBRARY_PATH

export PATH=/usr/local/cuda-11/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-11/lib64:$LD_LIBRARY_PATH
```

Running '../examples/train_model.py' now yields the following errors

Traceback (most recent call last):
  File "train_model.py", line 12, in <module>
    from graphnet.models import Model
  File "/lustre/hpc/icecube/qgf305/graphnet/src/graphnet/models/__init__.py", line 1, in <module>
    from .model import Model
  File "/lustre/hpc/icecube/qgf305/graphnet/src/graphnet/models/model.py", line 10, in <module>
    from torch_geometric.data import Data
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torch_geometric-2.0.1-py3.8.egg/torch_geometric/__init__.py", line 7, in <module>
    import torch_geometric.data
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torch_geometric-2.0.1-py3.8.egg/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torch_geometric-2.0.1-py3.8.egg/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torch_geometric-2.0.1-py3.8.egg/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torch_sparse-0.6.12-py3.8-linux-x86_64.egg/torch_sparse/__init__.py", line 15, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'

**Comment by MortenHolmRep** [comment]
At the moment I have a working environment, however, it was from copying an existing working environment. The working environment is pasted in at the bottom. In the interest of possibly problem-solving this issue in the future here is some steps taken

**A clean slate; Delete everything related to PyTorch and graphnet.**
`pip uninstall graphnet, torch, torch_lightning, torchgeometric, ...`

Trying to install Cuda specific versions of torch instead of default torch and I've tried two versions.
The first try was the most recent versions and follows the same approach as below, the version numbers will be marked with brackets [<install version>] below.

**A version known for working in the current framework (torch 1.9, cuda 11.1, courtesy of @RasmusOrsoe ) found at https://pytorch.org/get-started/previous-versions/**

`pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`
`[pip3 install torch==1.10.2+cu113 torchvision==0.11.3+cu113 torchaudio===0.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html]`

**Similarly, find the geometrics package found at https://download.pytorch.org/whl/torch_stable.html**

`pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.9.0+cu111.html`
`[pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.10.0+cu113.html]`

[when using the most recent packages this additionally resulted in a plotting error that requires an update of pandas
`pip install --upgrade pandas`
This issue might have been a problem for the earlier version as well, but I started with the most recent version]

**Reinstalling the graphnet package and running the example script** 
`cd graphnet/`
`python setup.py develop`

Rerunning ../examples/train_model.py
`python train_model.py`

The above still resulted in errors.
```
Traceback (most recent call last):
  File "train_model.py", line 13, in <module>
    from graphnet.models import Model
  File "/lustre/hpc/icecube/qgf305/graphnet/src/graphnet/models/__init__.py", line 1, in <module>
    from .model import Model
  File "/lustre/hpc/icecube/qgf305/graphnet/src/graphnet/models/model.py", line 10, in <module>
    from torch_geometric.data import Data
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torch_sparse/__init__.py", line 15, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/groups/icecube/qgf305/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.11: cannot open shared object file: No such file or directory
```

A combination of various version numbers of the export statements mentioned in an earlier post has been tried.
Right now I am still investigating a possible pathing issue with the Cuda export statements mentioned earlier that could be a cause.

Another **possible culprit can be the package "torch-spline-conv"**, which have been reported online as a possible issue.

**A possible solution could be using a mixture of conda and pip**, as pip apparently have a hard time recognising certain versions. However, at this time there is no clear answer.

A currently working environment:
```
name: gnn_py38_v2
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - asttokens=2.0.5=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - black=21.12b0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brotlipy=0.7.0=py38h497a2fe_1003
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py38h578d9bd_1
  - cffi=1.15.0=py38h3931269_0
  - chardet=4.0.0=py38h578d9bd_2
  - click=8.0.3=py38h578d9bd_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.0=py38h3e25421_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py38h709712a_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - executing=0.8.2=pyhd8ed1ab_0
  - fonttools=4.28.1=py38h497a2fe_0
  - freetype=2.10.4=h0708190_1
  - googledrivedownloader=0.4=pyhd3deb0d_1
  - idna=2.10=pyh9f0ad1d_0
  - ipykernel=6.7.0=py38he5a9106_0
  - ipython=8.0.1=py38h578d9bd_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py38h578d9bd_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py38h578d9bd_1
  - kiwisolver=1.3.2=py38h1fd1430_1
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libdeflate=1.8=h7f98852_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.3.0=h6f004c6_2
  - libuv=1.42.0=h7f98852_0
  - libwebp-base=1.2.1=h7f98852_0
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.0.1=py38h497a2fe_1
  - matplotlib-base=3.5.0=py38hf4fb855_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=0.4.3=py38h578d9bd_4
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - networkx=2.6.3=pyhd8ed1ab_1
  - ninja=1.10.2=h4bd325d_1
  - numpy=1.21.2=py38h20f2e39_0
  - numpy-base=1.21.2=py38h79a1101_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.4=py38h43a58ef_1
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py38h8e6f84c_0
  - pip=21.3.1=pyhd8ed1ab_0
  - platformdirs=2.3.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.26=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h578d9bd_4
  - python=3.8.12=hb7a2778_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-louvain=0.15=pyhd3deb0d_0
  - python_abi=3.8=2_cp38
  - pytorch=1.9.1=py3.8_cuda11.1_cudnn8.0.5_0
  - pytorch-cluster=1.5.9=py38_torch_1.9.0_cu111
  - pytorch-scatter=2.0.9=py38_torch_1.9.0_cu111
  - pytorch-sparse=0.6.12=py38_torch_1.9.0_cu111
  - pytorch-spline-conv=1.2.1=py38_torch_1.9.0_cu111
  - pytz=2021.3=pyhd8ed1ab_0
  - pyyaml=6.0=py38h497a2fe_3
  - pyzmq=22.3.0=py38h2035c66_1
  - readline=8.1=h46c0cb4_0
  - requests=2.25.1=pyhd3deb0d_0
  - scikit-learn=1.0.1=py38h51133e4_0
  - scipy=1.7.1=py38h292c36d_2
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h9cd32fc_2
  - stack_data=0.1.4=pyhd8ed1ab_0
  - tbb=2021.4.0=h4bd325d_1
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tk=8.6.11=h27826a3_1
  - tomli=1.2.2=pyhd8ed1ab_0
  - tornado=6.1=py38h497a2fe_2
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typed-ast=1.5.2=py38h497a2fe_0
  - typing_extensions=4.0.0=pyha770c72_0
  - unicodedata2=13.0.0.post2=py38h497a2fe_4
  - urllib3=1.26.7=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - alabaster==0.7.12
    - anybadge==1.8.0
    - astroid==2.9.3
    - async-timeout==4.0.2
    - attrs==21.4.0
    - babel==2.9.1
    - cachetools==5.0.0
    - charset-normalizer==2.0.10
    - configparser==5.2.0
    - coverage==6.3
    - dill==0.3.4
    - docker-pycreds==0.4.0
    - docutils==0.17.1
    - frozenlist==1.3.0
    - fsspec==2022.1.0
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.26
    - google-auth==2.5.0
    - google-auth-oauthlib==0.4.6
    - greenlet==1.1.2
    - grpcio==1.43.0
    - imagesize==1.3.0
    - importlib-metadata==4.10.1
    - iniconfig==1.1.1
    - isodate==0.6.0
    - isort==5.10.1
    - lazy-object-proxy==1.7.1
    - markdown==3.3.6
    - mccabe==0.6.1
    - multidict==6.0.2
    - oauthlib==3.1.1
    - pathtools==0.1.2
    - pluggy==1.0.0
    - promise==2.3
    - protobuf==3.19.3
    - psutil==5.9.0
    - py==1.11.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pylint==2.12.2
    - pytest==6.2.5
    - pytorch-lightning==1.5.9
    - rdflib==6.0.2
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - sentry-sdk==1.5.4
    - setuptools==59.5.0
    - shortuuid==1.0.8
    - smmap==5.0.0
    - snowballstemmer==2.2.0
    - sphinx==4.4.0
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sqlalchemy==1.4.27
    - subprocess32==3.5.4
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - timer==0.2.2
    - toml==0.10.2
    - torch-geometric==2.0.1
    - torchmetrics==0.7.0
    - versioneer==0.21
    - wandb==0.12.10
    - werkzeug==2.0.2
    - wheel==0.37.1
    - wrapt==1.13.3
    - yacs==0.1.8
    - yarl==1.7.2
    - yaspin==2.1.0
    - zipp==3.7.0
prefix: /groups/icecube/leonbozi/anaconda3/envs/gnn_py38
```

**Comment by asogaard** [comment]
Hi @MortenHolmRep,

Thanks for the detailed error report and for the steps to reproduce the error. I will try to reproduce and will revert here; in parallel, I will add a section to the README on installation.
